### ISSUE TITLE
All versions have "jupyter" header on my system, non-themable

### ISSUE THREAD

**Issue by the-efi** [nwhitehead/pineapple#34]
This happens with both 2.7 and 3.5 versions.
Theming does not work.
Note that I have a `brew`-ed Python 2.7 on my system with jupyter installed, but no 3.5 version.

<img width="1092" alt="pa" src="https://cloud.githubusercontent.com/assets/6472642/9975913/78485c6c-5ed6-11e5-8e02-cc1523f36953.png">

**Comment by bliker** [comment]
:+1: same issue

**Comment by nwhitehead** [comment]
I think the problem is user configuration files for Jupyter. When Pineapple starts it looks at the normal locations for configuration, and the existing Jupyter things are there. I made a change that makes Pineapple keep all it's configuration in separate directories to avoid interference. Please reopen this issue if the problem persists after the next release.
